module System.Win32.SystemServices.Services.SERVICE_ERROR
  ( SERVICE_ERROR (..)
  ) where

import Import
import Text.Printf
import System.Win32.SystemServices.Services.Types

data SERVICE_ERROR
  =  ERROR_SUCCESS
  |  ERROR_ACCESS_DENIED
  |  ERROR_DEPENDENT_SERVICES_RUNNING
  |  ERROR_INVALID_HANDLE
  |  ERROR_INVALID_PARAMETER
  |  ERROR_INVALID_SERVICE_CONTROL
  |  ERROR_SERVICE_CANNOT_ACCEPT_CTRL
  |  ERROR_SERVICE_NOT_ACTIVE
  |  ERROR_SERVICE_REQUEST_TIMEOUT
  |  ERROR_SHUTDOWN_IN_PROGRESS
  |  ERROR_INVALID_NAME
  |  ERROR_SERVICE_DOES_NOT_EXIST
  deriving (Show)

instance FromDWORD SERVICE_ERROR where
  fromDWORD x = case x of
    0x00000000 -> Right ERROR_SUCCESS
    0x00000005 -> Right ERROR_ACCESS_DENIED
    0x0000041B -> Right ERROR_DEPENDENT_SERVICES_RUNNING
    0x00000006 -> Right ERROR_INVALID_HANDLE
    0x00000057 -> Right ERROR_INVALID_PARAMETER
    0x0000045B -> Right ERROR_INVALID_SERVICE_CONTROL
    0x00000425 -> Right ERROR_SERVICE_CANNOT_ACCEPT_CTRL
    0x00000426 -> Right ERROR_SERVICE_NOT_ACTIVE
    0x0000041D -> Right ERROR_SERVICE_REQUEST_TIMEOUT
    0x0000045B -> Right ERROR_SHUTDOWN_IN_PROGRESS
    0x0000007B -> Right ERROR_INVALID_NAME
    0x00000424 -> Right ERROR_SERVICE_DOES_NOT_EXIST
    _          -> Left $ "The " ++ printf "%x" x ++ " error code is unsupported by this bindign."
