module System.Win32.SystemServices.Services.SVC_ACCESS_RIGHTS
  ( SVC_ACCESS_RIGHTS (..)
  , toDWORD
  , fromDWORD
  , sarToDword
  , sarFromDword
  , flag
  ) where

import Data.Bits
import Data.Maybe
import System.Win32.Types
import Text.Printf
import Import

data SVC_ACCESS_RIGHTS
  = SVC_AR_ALL_ACCESS
  | SVC_AR_CHANGE_CONFIG
  | SVC_AR_ENUMERATE_DEPENDENTS
  | SVC_AR_INTERROGATE
  | SVC_AR_PAUSE_CONTINUE
  | SVC_AR_QUERY_CONFIG
  | SVC_AR_QUERY_STATUS
  | SVC_AR_START
  | SVC_AR_STOP
  | SVC_AR_USER_DEFINED_CONTROL
  | SVC_AR_OTHER DWORD
  deriving (Show)

toDWORD :: SVC_ACCESS_RIGHTS -> DWORD
toDWORD SVC_AR_ALL_ACCESS            = 0x000F01FF
toDWORD SVC_AR_CHANGE_CONFIG         = 0x00000002
toDWORD SVC_AR_ENUMERATE_DEPENDENTS  = 0x00000008
toDWORD SVC_AR_INTERROGATE           = 0x00000080
toDWORD SVC_AR_PAUSE_CONTINUE        = 0x00000040
toDWORD SVC_AR_QUERY_CONFIG          = 0x00000001
toDWORD SVC_AR_QUERY_STATUS          = 0x00000004
toDWORD SVC_AR_START                 = 0x00000010
toDWORD SVC_AR_STOP                  = 0x00000020
toDWORD SVC_AR_USER_DEFINED_CONTROL  = 0x00000100
toDWORD (SVC_AR_OTHER x) = x

fromDWORD :: DWORD -> SVC_ACCESS_RIGHTS
fromDWORD 0x000F01FF = SVC_AR_ALL_ACCESS
fromDWORD 0x00000002 = SVC_AR_CHANGE_CONFIG
fromDWORD 0x00000008 = SVC_AR_ENUMERATE_DEPENDENTS
fromDWORD 0x00000080 = SVC_AR_INTERROGATE
fromDWORD 0x00000040 = SVC_AR_PAUSE_CONTINUE
fromDWORD 0x00000001 = SVC_AR_QUERY_CONFIG
fromDWORD 0x00000004 = SVC_AR_QUERY_STATUS
fromDWORD 0x00000010 = SVC_AR_START
fromDWORD 0x00000020 = SVC_AR_STOP
fromDWORD 0x00000100 = SVC_AR_USER_DEFINED_CONTROL
fromDWORD x = SVC_AR_OTHER x

sarToDword :: SVC_ACCESS_RIGHTS -> DWORD
sarToDword = toDWORD

sarFromDword :: DWORD -> SVC_ACCESS_RIGHTS
sarFromDword = fromDWORD

flag :: [SVC_ACCESS_RIGHTS] -> DWORD
flag = foldl (\flag' f -> flag' .|. toDWORD f) 0
